[pytest]
DJANGO_SETTINGS_MODULE = my_cloud_project.settings

markers =
    api: тесты, взаимодействующие с API
    units: модульные тесты (изолированные, с моками)
    django_db: тесты, требующие доступа к БД Django
